"""add core tables

Revision ID: c92c8d58d39a
Revises: f1b8da416d30
Create Date: 2026-07-06 20:24:11.168122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92c8d58d39a'
down_revision: Union[str, Sequence[str], None] = 'f1b8da416d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('tg_username', sa.String(length=100), nullable=False),
    sa.Column('university', sa.String(length=500), nullable=False),
    sa.Column('direction', sa.String(length=500), nullable=False),
    sa.Column('course_number', sa.Integer(), nullable=False),
    sa.Column('math_score', sa.Integer(), nullable=False),
    sa.Column('russ_score', sa.Integer(), nullable=False),
    sa.Column('phys_score', sa.Integer(), nullable=True),
    sa.Column('inf_score', sa.Integer(), nullable=True),
    sa.Column('student_ticket', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), server_default=sa.text("'curator'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curators_phone_number'), 'curators', ['phone_number'], unique=True)
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parents_phone_number'), 'parents', ['phone_number'], unique=True)
    op.create_table('psychologists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=False),
    sa.Column('profession', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('tg_username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('education', sa.String(length=100), nullable=False),
    sa.Column('exp_number_years', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psychologists_phone_number'), 'psychologists', ['phone_number'], unique=True)
    op.add_column('students', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('students', sa.Column('curator_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('psychologist_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('students', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_students_phone_number'), 'students', ['phone_number'], unique=True)
    op.create_foreign_key(None, 'students', 'parents', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'students', 'curators', ['curator_id'], ['id'])
    op.create_foreign_key(None, 'students', 'psychologists', ['psychologist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_index(op.f('ix_students_phone_number'), table_name='students')
    op.drop_column('students', 'created_at')
    op.drop_column('students', 'image_url')
    op.drop_column('students', 'parent_id')
    op.drop_column('students', 'psychologist_id')
    op.drop_column('students', 'curator_id')
    op.drop_column('students', 'phone_number')
    op.drop_column('students', 'last_name')
    op.drop_index(op.f('ix_psychologists_phone_number'), table_name='psychologists')
    op.drop_table('psychologists')
    op.drop_index(op.f('ix_parents_phone_number'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_curators_phone_number'), table_name='curators')
    op.drop_table('curators')
    # ### end Alembic commands ###
